"""
File operations for schema synchronization.

This module contains methods for updating schema files, version management,
and file system operations related to schema synchronization.
"""

import hashlib
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from .base import Colors


class FileOperations:
    """Handles file operations for schema synchronization."""

    def __init__(self, schemas_dir: Path):
        self.schemas_dir = schemas_dir

    def calculate_schema_hash(self, schema: dict) -> str:
        """Calculate SHA256 hash of schema."""
        schema_json = json.dumps(schema, sort_keys=True)
        return hashlib.sha256(schema_json.encode()).hexdigest()

    def update_version_file(self):
        """Update schema_version.py with new version info."""
        version_file = self.schemas_dir / "schema_version.py"

        version_info = {
            "version": datetime.now(UTC).isoformat(),
            "hash": self.calculate_schema_hash({}),  # Will be updated with actual schema
            "timestamp": datetime.now(UTC).timestamp(),
        }

        version_content = f'''"""
Schema version information.

Auto-generated by schema sync.
"""

VERSION = "{version_info["version"]}"
HASH = "{version_info["hash"]}"
TIMESTAMP = {version_info["timestamp"]}
'''

        version_file.write_text(version_content)
        print(f"{Colors.GREEN}Updated schema_version.py{Colors.END}")

    def prune_schema_snapshots(self, keep: int = 1):
        """Remove old schema snapshots, keeping only the most recent ones."""
        snapshots_dir = self.schemas_dir / "snapshots"
        if not snapshots_dir.exists():
            return

        snapshot_files = list(snapshots_dir.glob("schema_*.json"))
        snapshot_files.sort(key=lambda f: f.stat().st_mtime, reverse=True)

        # Keep only the most recent files
        files_to_remove = snapshot_files[keep:]

        for file_path in files_to_remove:
            file_path.unlink()
            print(f"{Colors.YELLOW}Removed old snapshot: {file_path.name}{Colors.END}")

    def save_schema_snapshot(self, schema: dict[str, Any]):
        """Save a snapshot of the current schema."""
        snapshots_dir = self.schemas_dir / "snapshots"
        snapshots_dir.mkdir(exist_ok=True)

        timestamp = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
        snapshot_file = snapshots_dir / f"schema_{timestamp}.json"

        with snapshot_file.open("w") as f:
            json.dump(schema, f, indent=2, default=str)

        print(f"{Colors.BLUE}Saved schema snapshot: {snapshot_file.name}{Colors.END}")
