# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: false
  tables: false
  headings: true
  strict: false
  stern: false

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements:
    - br
    - details
    - summary
    - sup
    - sub

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false

# MD046/code-block-style - Code block style
MD046:
  style: fenced

