services:
  - type: web
    name: atoms-mcp-server
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      # Transport mode
      - key: ATOMS_FASTMCP_TRANSPORT
        value: http
      - key: ATOMS_FASTMCP_PORT
        value: 8000
      - key: ATOMS_FASTMCP_HOST
        value: 0.0.0.0
      - key: ATOMS_FASTMCP_HTTP_PATH
        value: /api/mcp

      # Auto-filled by Render
      - key: ATOMS_FASTMCP_PUBLIC_BASE_URL
        sync: false  # Set this manually in Render dashboard to https://your-app.onrender.com

      # Supabase (add these as secret environment variables in Render dashboard)
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false

      # WorkOS/AuthKit (add as secret environment variables)
      - key: FASTMCP_SERVER_AUTH_AUTHKITPROVIDER_AUTHKIT_DOMAIN
        sync: false
      - key: WORKOS_API_KEY
        sync: false

      # Optional
      - key: WORKOS_API_URL
        value: https://api.workos.com

      # Google Cloud / Vertex AI (add as secret environment variables)
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_CLOUD_LOCATION
        value: us-central1
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false  # Path to service account JSON file or set credentials directly

    # Health check
    healthCheckPath: /health

    # Auto-deploy on push
    autoDeploy: true
