"""
Cloud provider abstraction layer for multi-cloud deployments.

This package provides a unified interface for deploying and managing resources
across multiple cloud providers including AWS, GCP, Azure, Vercel, Render,
Supabase, Fly.io, Neon, and PlanetScale.
"""

from .types import (
    ResourceType,
    DeploymentState,
    DeploymentStrategy,
    Capability,
    HealthStatus,
    ResourceConfig,
    DeployConfig,
    HealthCheckConfig,
    RollbackConfig,
    Resource,
    Endpoint,
    DeploymentConfig,
    DeploymentSource,
    Deployment,
    DeploymentError,
    DeploymentStatus,
    InstanceInfo,
    ResourceFilter,
    LogOptions,
    LogEntry,
    MetricOptions,
    Metric,
    CostEstimate,
    Cost,
    TimeRange,
    Credentials,
    ProviderMetadata,
    Region,
    ScaleConfig,
    ScalePolicy,
    BackupConfig,
    Backup,
)

from .interfaces import (
    CloudProvider,
    Scalable,
    Loggable,
    Executable,
    Backupable,
    Monitorable,
    DatabaseProvider,
    ProviderRegistry,
    DeploymentOrchestrator,
)

from .errors import (
    ErrorCategory,
    CloudError,
    AuthenticationError,
    QuotaError,
    ValidationError,
    ResourceNotFoundError,
    ConflictError,
    ProvisioningError,
    NetworkError,
    InternalProviderError,
    NotSupportedError,
    RetryConfig,
    DefaultRetryConfig,
    should_retry,
    calculate_backoff,
)

from .registry import (
    get_registry,
    register_provider,
    unregister_provider,
    get_provider,
    list_providers,
    get_provider_info,
)

__all__ = [
    # Types
    "ResourceType",
    "DeploymentState",
    "DeploymentStrategy",
    "Capability",
    "HealthStatus",
    "ResourceConfig",
    "DeployConfig",
    "HealthCheckConfig",
    "RollbackConfig",
    "Resource",
    "Endpoint",
    "DeploymentConfig",
    "DeploymentSource",
    "Deployment",
    "DeploymentError",
    "DeploymentStatus",
    "InstanceInfo",
    "ResourceFilter",
    "LogOptions",
    "LogEntry",
    "MetricOptions",
    "Metric",
    "CostEstimate",
    "Cost",
    "TimeRange",
    "Credentials",
    "ProviderMetadata",
    "Region",
    "ScaleConfig",
    "ScalePolicy",
    "BackupConfig",
    "Backup",
    # Interfaces
    "CloudProvider",
    "Scalable",
    "Loggable",
    "Executable",
    "Backupable",
    "Monitorable",
    "DatabaseProvider",
    "ProviderRegistry",
    "DeploymentOrchestrator",
    # Errors
    "ErrorCategory",
    "CloudError",
    "AuthenticationError",
    "QuotaError",
    "ValidationError",
    "ResourceNotFoundError",
    "ConflictError",
    "ProvisioningError",
    "NetworkError",
    "InternalProviderError",
    "NotSupportedError",
    "RetryConfig",
    "DefaultRetryConfig",
    "should_retry",
    "calculate_backoff",
    # Registry
    "get_registry",
    "register_provider",
    "unregister_provider",
    "get_provider",
    "list_providers",
    "get_provider_info",
]

__version__ = "1.0.0"
