#!/usr/bin/env python3
"""Generate Pydantic models from Supabase schema.

This script uses supabase-pydantic to introspect the Supabase database
and generate type-safe Pydantic models for all tables.

Usage:
    python scripts/generate_schemas.py

Environment variables required:
    SUPABASE_URL - Your Supabase project URL
    SUPABASE_SERVICE_KEY - Service role key (for schema introspection)
"""

import os
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

def generate_schemas():
    """Generate Pydantic models from Supabase database schema."""
    
    # Check environment variables
    supabase_url = os.getenv("SUPABASE_URL")
    supabase_key = os.getenv("SUPABASE_SERVICE_KEY") or os.getenv("SUPABASE_KEY")
    
    if not supabase_url:
        print("❌ Error: SUPABASE_URL environment variable not set")
        sys.exit(1)
    
    if not supabase_key:
        print("❌ Error: SUPABASE_SERVICE_KEY or SUPABASE_KEY environment variable not set")
        sys.exit(1)
    
    print(f"🔍 Connecting to Supabase: {supabase_url}")
    
    try:
        from supabase_pydantic import create_pydantic_models
        from supabase import create_client
    except ImportError as e:
        print(f"❌ Error: Failed to import supabase-pydantic: {e}")
        print("   Install with: pip install supabase-pydantic")
        sys.exit(1)
    
    # Create Supabase client
    client = create_client(supabase_url, supabase_key)
    
    # Tables to generate models for
    tables = [
        "organizations",
        "projects",
        "documents",
        "requirements",
        "test_req",
        "blocks",
        "properties",
        "trace_links",
        "assignments",
        "profiles",
        "organization_members",
        "project_members",
        "organization_invitations",
        "requirement_tests",
        "audit_logs",
        "notifications",
        "external_documents",
        "test_matrix_views",
        "mcp_sessions",
    ]
    
    # Create output directory
    output_dir = Path("schemas/generated")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"📁 Output directory: {output_dir}")
    print(f"📊 Generating models for {len(tables)} tables...")
    
    # Generate models for each table
    generated_models = []
    
    for table in tables:
        try:
            print(f"  ⏳ Generating {table}...")
            
            # Use supabase-pydantic to generate model
            models = create_pydantic_models(
                client,
                table_name=table,
                schema="public"
            )
            
            # Get the model class
            model_class = models[0] if isinstance(models, list) else models
            model_name = model_class.__name__
            
            generated_models.append((table, model_name, model_class))
            print(f"  ✅ Generated {model_name}")
            
        except Exception as e:
            print(f"  ⚠️  Warning: Failed to generate {table}: {e}")
            continue
    
    # Write models to file
    output_file = output_dir / "models.py"
    
    with open(output_file, "w") as f:
        f.write('"""Auto-generated Pydantic models from Supabase schema.\n\n')
        f.write('DO NOT EDIT THIS FILE MANUALLY!\n')
        f.write('Generated by: scripts/generate_schemas.py\n')
        f.write('"""\n\n')
        f.write('from datetime import datetime\n')
        f.write('from typing import Any, Optional\n')
        f.write('from uuid import UUID\n')
        f.write('from pydantic import BaseModel, Field\n\n')
        
        # Write each model
        for table, model_name, model_class in generated_models:
            f.write(f'# Model for table: {table}\n')
            f.write(f'class {model_name}(BaseModel):\n')
            
            # Get model fields
            for field_name, field_info in model_class.model_fields.items():
                field_type = field_info.annotation
                f.write(f'    {field_name}: {field_type}\n')
            
            f.write('\n    class Config:\n')
            f.write('        from_attributes = True\n\n\n')
    
    # Create __init__.py
    init_file = output_dir / "__init__.py"
    with open(init_file, "w") as f:
        f.write('"""Auto-generated Pydantic models from Supabase."""\n\n')
        f.write('from .models import (\n')
        for _, model_name, _ in generated_models:
            f.write(f'    {model_name},\n')
        f.write(')\n\n')
        f.write('__all__ = [\n')
        for _, model_name, _ in generated_models:
            f.write(f'    "{model_name}",\n')
        f.write(']\n')
    
    print(f"\n✅ Successfully generated {len(generated_models)} models")
    print(f"📄 Output: {output_file}")
    print(f"📄 Exports: {init_file}")
    print("\n🎉 Schema generation complete!")

if __name__ == "__main__":
    generate_schemas()

