"""
Schema Version Tracking

This file is auto-generated by scripts/sync_schema.py
DO NOT EDIT MANUALLY
"""

SCHEMA_VERSION = "2025-10-09"
LAST_SYNC = "2025-10-09T22:58:57.925107+00:00"
DB_HASH = "08bf3e4c7004b43dd6c3a72e1f413d0064511cd1b9aef56184e3f4a05bbaf3cb"

# Schema statistics
TABLES_COUNT = 38
ENUMS_COUNT = 40

# Last sync differences count
LAST_SYNC_DIFFERENCES = 84
